# 关于 [[Python]] 的生成器（协程）的`yield`，以及`yield from`的心智模型
	- `yield`应当认为是**非原子的**，它是一个**两步**的操作：**向调用者返回一个值（或None）；暂停期待调用者的唤起**。在唤起之前，生成器中当前执行的代码始终是`yield XXX`，**协程在`yield`内部暂停**。
	- **调用者唤起协程时，会向协程传递特定的值或者异常，然后控制权交给协程去继续执行；倘若是传递特定的值，则该值会作为`yield`语句的返回值返回过来；倘若是传递异常，则异常会直接从`field`语句位置抛出**。
	- 唤起协程有三种方式——协程的`send`和`throw`方法，以及`next`函数：
		- `send`：传递给协程一个值，执行直到遇到下一个`yield`或完成执行，倘若是前者，返回下一个`yield`传过来的值。
		- `throw`：接受异常或异常类型，让协程在`yield`内部抛出异常，期待生成器的捕获，并继续执行（同`send`），使用生成器函数定义上下文管理器时内置库会使用该操作。
		- `next`：等价于`send(None)`。
		- `close`：等价于抛出`GeneratorExit`异常，这个异常相当基础（甚至不是Exception的子类），一般来说不能被捕获到，同时它也不会在调用方产生异常。
	- 此外，刚创建的生成器不能执行`send(非None值)`，这是符合逻辑的——没有人去接受它。但能抛出异常……此时生成器无法捕获它，它会立刻被传播回调用者，很有趣的设计。创建协程后第一次执行`next`时会激活协程，这一步称为**预激**（prime），一些框架提供装饰器会在创建时自动预激协程，但`yield from`语法是会自动预激协程的……？
	- 协程结束执行后，**它return的值会作为所抛出的StopIteration异常的value字段**，注意return的值是无法通过next获取到的，**因此它也不会出现在for中**。
	- `yield from`原本是在生成器中直接使用其它生成器，它的原理可以表示为：
	- ```python
	  yield from x
	  # 等价于
	  for i in x:
	      yield i
	  ```
	- 但考虑到协程是可以喂给它值的，现在事情变得复杂了。`yield from`现在应当理解为，**委派（delegate）**工作给**子生成器**，这个委派和其他语言的委派概念一样——**实际工作不是我干的，我只接受它的结果，操作我就是操作我委派的那家伙**。**同时，`yield from`的返回值即为子生成器return的值**。
	- 实际上，`yield from`，其行为就**等于把子生成器的代码原样拷过来一份，并把最后的return返回出来**。`yield`无法直接地实现`yield from`，**后者允许用户喂进来的值以及产出的值直接跨越嵌套的子生成器**。
	- ```python
	  def co(name: str):
	      for i in range(3):
	          x = yield
	          print(name + ' coroutine received ' + x)
	      return name + ' DONE!'
	  
	  
	  def f():
	      a: str = yield from co('me')
	      print('me finished, response: ', a)
	      b: str = yield from co('you')
	      print('you finished, response: ', b)
	      return 'wtf'
	  
	  c = f()
	  next(c)
	  c.send('hello') # me coroutine received hello
	  c.send('world') # me coroutine received world
	  c.send('abc') # me coroutine received abc
	  # me finished, response:  me DONE!
	  
	  c.send('hello') # me coroutine received hello
	  c.send('world') # me coroutine received world
	  c.send('abc') # me coroutine received abc
	  # StopIteration: wtf
	  ```
- # 关于 [[Python]] 的上下文管理器，以及`contextlib.contextmanager`的实现
	- 上下文管理器本质上就是，对 `with XXX （as f）`：调用XXX的`__enter__`方法，将其返回值赋给f；执行with的代码体，待执行完后或者抛出异常时，执行XXX的`__exit__`方法，异常信息通过三个参数传入`__exit__`——异常类exc_type，异常类实例exc_value，以及调用栈信息traceback；**若异常发生且`__exit__`返回值非True，冒泡异常**。
	- 但`contextlib.contextmanager`允许使用生成器函数去写上下文管理器，下面是一个计时器例子，其中能够在执行中插入“桩”：
		- ```python
		  import contextlib
		  from time import perf_counter
		  from typing import Dict
		  
		  # 使用类的方式
		  class TimeIt:
		      def __init__(self, name: str) -> None:
		          self.name = name
		          self.start_time: float = None
		          self.moments: Dict[str, float] = {}
		      def __enter__(self):
		          self.start_time = perf_counter()
		          def add_moment(moment_name: str):
		              if moment_name in self.moments or moment_name == self.name:
		                  raise KeyError(f'duplicate moment "{moment_name}"')
		              self.moments[moment_name] = perf_counter()
		          return add_moment # 该结果会被as反过去
		  
		      def __exit__(self, *excinfo):
		          self.moments[self.name] = perf_counter()
		          for name, moment in self.moments.items():
		              cost_ms = (moment - self.start_time) * 1000
		              print(f"{name}: {cost_ms} ms")
		          # return True # 如果return True，异常会被屏蔽如果发生异常，计时器不应当屏蔽异常
		  
		  
		  with TimeIt('hello') as timer:
		      timer('start') # 中途记录时间点
		      print('wtf')
		      timer('moment1')
		      print('wtf')
		  
		  # 使用生成器函数的方式
		  @contextlib.contextmanager
		  def TimeIt(name: str):
		    	# __enter
		      start_time = perf_counter()
		      moments: Dict[str, float] = {}
		      def add_moment(moment_name: str):
		          if moment_name in moments or moment_name == name:
		              raise KeyError(f'duplicate moment "{moment_name}"')
		          moments[moment_name] = perf_counter()
		      try:
		          yield add_moment # yield的值会被传回去
		      finally:
		          # __exit__
		          moments[name] = perf_counter()
		          for name, moment in moments.items():
		              cost_ms = (moment - start_time) * 1000
		              print(f"{name}: {cost_ms} ms")
		  
		  with TimeIt('hello') as timer:
		      timer('start') # 中途记录时间点
		      print('wtf')
		      timer('moment1')
		      print('wtf')
		  ```
	- 现在自己实现一个contextmanager作为学习。首先需要明确它的行为：
		- contextmanager接受一个生成器函数（说成是生成器工厂更合适），返回一个返回上下文管理器的函数（替换掉原函数的定义，这样原函数调用后就得到一个上下文管理器）
		  logseq.order-list-type:: number
		- 原函数被调用时，创建相应上下文管理器，其中创建生成器实例（`__init__`时创建还是`__enter__`时创建无关紧要）
		  logseq.order-list-type:: number
		- 进入上下文，`__enter__`被调用，此时需要执行`next`，执行生成器中yield之前的部分，并得到yield的值，返回出来
		  logseq.order-list-type:: number
		- with子句执行，执行完毕或抛出异常后进入`__exit__`
		  logseq.order-list-type:: number
		- `__exit__`检查with子句中是否抛出异常，倘若没有抛出异常，就再次调用`next`，执行生成器中yield之后的部分，并期待得到一个`StopIteration`，否则证明生成器编写错误，出现了多个yield
		  logseq.order-list-type:: number
		- 倘若抛出异常，要把异常传给生成器（`gen.throw(exc_value)`），检查生成器正常结束——此时有三种可能：
		  logseq.order-list-type:: number
			- 生成器抛出StopIteration，说明生成器处理掉了异常，并正常关闭
			  logseq.order-list-type:: number
			- 生成器抛出其他异常，说明生成器处理过程中发生异常或者传给生成器的异常被原样返回，此时任由它冒泡
			  logseq.order-list-type:: number
			- 生成器没有抛出异常，这证明生成器编写错误，出现了多个yield
			  logseq.order-list-type:: number
		- 有一些边缘情况需要考虑（如处理异常时要检查StopIteration是生成器抛出来的还是with子句中抛出来的），以及traceback需要维护，这里直接无视。
		- ```python
		  import contextlib
		  from time import perf_counter
		  from typing import Any, Callable, Generator
		  import functools
		  
		  def ContextManager(fn):
		      class _RealContextManager:
		          def __init__(self, gen: Generator) -> None:
		              self.gen = gen
		          def __enter__(self):
		              # 执行__enter__，把yield的值传出来，给with子句去
		              value = next(self.gen)
		              return value
		          
		          # 然后，with子句执行……来到 exit
		          def __exit__(self, type, value, tb):
		              # 如果没有发生异常，就让生成器继续执行，这时候期待一个 StopIteration
		              if type is None:
		                  try:
		                      next(self.gen)
		                  except StopIteration: # 生成器正常结束，这里没有异常所以直接 return 就行
		                      return True
		                  else: # 居然没有StopIteration，这时候就说明生成器里有多个yield，该上下文管理器的定义是非法的
		                      raise RuntimeError("generator not terminated!")
		              
		              # 如果发生异常，通知生成器去处理
		              # 倘若生成器编写正确，这里将抛出一个 StopIteration，或者抛出这里抛给它的异常
		              try:
		                  self.gen.throw(value) # 这里value可能为None，此时需要使用type()再次构造异常
		              except StopIteration: # 生成器正常结束，也就是说它正确处理了这里抛出的异常，因此抑制这里的异常
		                  return True
		              else: # 居然没有StopIteration，这时候同样说明生成器里有多个yield，定义非法
		                  raise RuntimeError("generator not terminated when exception is thrown!")
		      @functools.wraps(fn)
		      def func(*args, **kwargs):
		          return _RealContextManager(fn(*args, **kwargs))
		      return func
		  
		  @ContextManager
		  def TimeIt(name: str):
		    	# __enter
		      start_time = perf_counter()
		      try:
		          yield
		      except RuntimeError as e:
		          print('error happened!')
		      finally:
		          # __exit__
		          end_time = perf_counter()
		          print(f"{name} costs: {(end_time - start_time) * 1000:.6f} ms")
		  
		  with TimeIt('hello'):
		      print('hello')
		  ```